/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RoleInsightsRouteImport } from './routes/role-insights'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PostSignupRouteImport } from './routes/post-signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CancellationRouteImport } from './routes/cancellation'
import { Route as AiSecretaryRouteImport } from './routes/ai-secretary'
import { Route as AiCounselorRouteImport } from './routes/ai-counselor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportReportIdRouteImport } from './routes/report.$reportId'
import { Route as PaymentReturnRouteImport } from './routes/payment.return'
import { Route as CheckoutShareTokenRouteImport } from './routes/checkout_.$shareToken'
import { Route as AdminSecurityRouteImport } from './routes/admin_.security'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleInsightsRoute = RoleInsightsRouteImport.update({
  id: '/role-insights',
  path: '/role-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PostSignupRoute = PostSignupRouteImport.update({
  id: '/post-signup',
  path: '/post-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationRoute = CancellationRouteImport.update({
  id: '/cancellation',
  path: '/cancellation',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSecretaryRoute = AiSecretaryRouteImport.update({
  id: '/ai-secretary',
  path: '/ai-secretary',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCounselorRoute = AiCounselorRouteImport.update({
  id: '/ai-counselor',
  path: '/ai-counselor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportReportIdRoute = ReportReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => ReportRoute,
} as any)
const PaymentReturnRoute = PaymentReturnRouteImport.update({
  id: '/payment/return',
  path: '/payment/return',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutShareTokenRoute = CheckoutShareTokenRouteImport.update({
  id: '/checkout_/$shareToken',
  path: '/checkout/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/admin_/security',
  path: '/admin/security',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRoute
  '/ai-counselor': typeof AiCounselorRoute
  '/ai-secretary': typeof AiSecretaryRoute
  '/cancellation': typeof CancellationRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/post-signup': typeof PostSignupRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRouteWithChildren
  '/role-insights': typeof RoleInsightsRoute
  '/terms': typeof TermsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/checkout/$shareToken': typeof CheckoutShareTokenRoute
  '/payment/return': typeof PaymentReturnRoute
  '/report/$reportId': typeof ReportReportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRoute
  '/ai-counselor': typeof AiCounselorRoute
  '/ai-secretary': typeof AiSecretaryRoute
  '/cancellation': typeof CancellationRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/post-signup': typeof PostSignupRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRouteWithChildren
  '/role-insights': typeof RoleInsightsRoute
  '/terms': typeof TermsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/checkout/$shareToken': typeof CheckoutShareTokenRoute
  '/payment/return': typeof PaymentReturnRoute
  '/report/$reportId': typeof ReportReportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRoute
  '/ai-counselor': typeof AiCounselorRoute
  '/ai-secretary': typeof AiSecretaryRoute
  '/cancellation': typeof CancellationRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/post-signup': typeof PostSignupRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRouteWithChildren
  '/role-insights': typeof RoleInsightsRoute
  '/terms': typeof TermsRoute
  '/admin_/security': typeof AdminSecurityRoute
  '/checkout_/$shareToken': typeof CheckoutShareTokenRoute
  '/payment/return': typeof PaymentReturnRoute
  '/report/$reportId': typeof ReportReportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/admin'
    | '/ai-counselor'
    | '/ai-secretary'
    | '/cancellation'
    | '/checkout'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/post-signup'
    | '/privacy'
    | '/report'
    | '/role-insights'
    | '/terms'
    | '/admin/security'
    | '/checkout/$shareToken'
    | '/payment/return'
    | '/report/$reportId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/admin'
    | '/ai-counselor'
    | '/ai-secretary'
    | '/cancellation'
    | '/checkout'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/post-signup'
    | '/privacy'
    | '/report'
    | '/role-insights'
    | '/terms'
    | '/admin/security'
    | '/checkout/$shareToken'
    | '/payment/return'
    | '/report/$reportId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/admin'
    | '/ai-counselor'
    | '/ai-secretary'
    | '/cancellation'
    | '/checkout'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/post-signup'
    | '/privacy'
    | '/report'
    | '/role-insights'
    | '/terms'
    | '/admin_/security'
    | '/checkout_/$shareToken'
    | '/payment/return'
    | '/report/$reportId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AdminRoute: typeof AdminRoute
  AiCounselorRoute: typeof AiCounselorRoute
  AiSecretaryRoute: typeof AiSecretaryRoute
  CancellationRoute: typeof CancellationRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PostSignupRoute: typeof PostSignupRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportRoute: typeof ReportRouteWithChildren
  RoleInsightsRoute: typeof RoleInsightsRoute
  TermsRoute: typeof TermsRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  CheckoutShareTokenRoute: typeof CheckoutShareTokenRoute
  PaymentReturnRoute: typeof PaymentReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role-insights': {
      id: '/role-insights'
      path: '/role-insights'
      fullPath: '/role-insights'
      preLoaderRoute: typeof RoleInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-signup': {
      id: '/post-signup'
      path: '/post-signup'
      fullPath: '/post-signup'
      preLoaderRoute: typeof PostSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation': {
      id: '/cancellation'
      path: '/cancellation'
      fullPath: '/cancellation'
      preLoaderRoute: typeof CancellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-secretary': {
      id: '/ai-secretary'
      path: '/ai-secretary'
      fullPath: '/ai-secretary'
      preLoaderRoute: typeof AiSecretaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-counselor': {
      id: '/ai-counselor'
      path: '/ai-counselor'
      fullPath: '/ai-counselor'
      preLoaderRoute: typeof AiCounselorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$reportId': {
      id: '/report/$reportId'
      path: '/$reportId'
      fullPath: '/report/$reportId'
      preLoaderRoute: typeof ReportReportIdRouteImport
      parentRoute: typeof ReportRoute
    }
    '/payment/return': {
      id: '/payment/return'
      path: '/payment/return'
      fullPath: '/payment/return'
      preLoaderRoute: typeof PaymentReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout_/$shareToken': {
      id: '/checkout_/$shareToken'
      path: '/checkout/$shareToken'
      fullPath: '/checkout/$shareToken'
      preLoaderRoute: typeof CheckoutShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/security': {
      id: '/admin_/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReportRouteChildren {
  ReportReportIdRoute: typeof ReportReportIdRoute
}

const ReportRouteChildren: ReportRouteChildren = {
  ReportReportIdRoute: ReportReportIdRoute,
}

const ReportRouteWithChildren =
  ReportRoute._addFileChildren(ReportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AdminRoute: AdminRoute,
  AiCounselorRoute: AiCounselorRoute,
  AiSecretaryRoute: AiSecretaryRoute,
  CancellationRoute: CancellationRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PostSignupRoute: PostSignupRoute,
  PrivacyRoute: PrivacyRoute,
  ReportRoute: ReportRouteWithChildren,
  RoleInsightsRoute: RoleInsightsRoute,
  TermsRoute: TermsRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  CheckoutShareTokenRoute: CheckoutShareTokenRoute,
  PaymentReturnRoute: PaymentReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
